export const STORE_USER = "STORE_USER";
export const REMOVE_USER = "REMOVE_USER";
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
